### ISSUE TITLE
Missing .gz support

### ISSUE THREAD

**Issue by kpcyrd** [winebarrel/fluent-plugin-elb-access-log#8]
I troubleshooted this plugin because it didn't do anything and didn't log anything at all (even with debug output)
```
          if logfile_suffix !~ /\.log\z/ or logfile_datetime <= (timestamp - @buffer_sec)
            next
          end
```
It turned out there's no .gz support and it's just ignoring all files ending instead.

**Comment by winebarrel** [comment]
Sorry for late.
I added support for .gz.
Please try v0.3.7

**Comment by winebarrel** [comment]
Sorry
v0.3.7 has a bug.
try 0.4.1
